rango/urls.py
from django.urls import path
from rango import views


app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/add_page/',
                 views.add_page, name='add_page'),
    path('category/<slug:category_name_slug>/', views.show_category,
         name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('/rango/category/<slug:category_name_slug>/add_page/)',views.add_page,name = 'add_page')
]

tango_with_django_project/urls.py
from django.contrib import admin 
from django.urls import path 
from django.urls import include 
from rango import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page,
            name='add_page'),
    path('category/<slug:category_name_slug>/', views.show_category,
        name='show_category'),
    path('add_category/', views.add_category, name='add_category'), path('register/', views.register, name='register'), # New mapping!
]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True) 
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) 
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    
    def __str__(self): 
        return self.title

class UserProfile(models.Model):
# This line is required. Links UserProfile to a User model instance. 
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

def __str__(self):
    return self.user.username

rango/forms.py
from django import forms
from rango.models import Page,Category
from django.contrib.auth.models import User 
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                          help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
# Provide an association
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                           help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,

                        help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    def clean(self):
        cleaned_data = self.cleaned_data 
        url = cleaned_data.get('url')
# If url is not empty and doesn't start with 'http://', # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

    class Meta:
# Provide an association between the ModelForm and a model 
        model = Page
# What fields do we want to include in our form?
# This way we don't need every field in the model present.
# Some fields may allow NULL values; we may not want to include them. # Here, we are hiding the foreign key.
# we can either exclude the category field from the form,
        exclude = ('category',)
# or specify the fields to include (don't include the category field). #fields = ('title', 'url', 'views')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta: 
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm): 
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from rango.forms import PageForm
from django.shortcuts import redirect 
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login 
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login, logout
from datetime import datetime


def index(request):
    category_list = Category.objects.order_by('-likes')[:5] 
    page_list = Page.objects.order_by('-views')[:5]
    
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']  

    response = render(request, 'rango/index.html', context=context_dict) 
    return response



def about(request):
    context_dict = {'boldmessage':'crunchy, creamy, cookie, candy, cupcake!'}
    return render(request, 'rango/about.html', context=context_dict)   

def show_category(request, category_name_slug):
# Create a context dictionary which we can pass # to the template rendering engine. 
    context_dict = {}
    try:
# Can we find a category name slug with the given name?
# If we can't, the .get() method raises a DoesNotExist exception.
# The .get() method returns one model instance or raises an exception. 
        category = Category.objects.get(slug=category_name_slug)
# Retrieve all of the associated pages.
# The filter() will return a list of page objects or an empty list. 
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
# We also add the category object from
# the database to the context dictionary.
# We'll use this in the template to verify that the category exists. 
        context_dict['category'] = category
    except Category.DoesNotExist:
# We get here if we didn't find the specified category.
# Don't do anything -
# the template will display the "no category" message for us. 
        context_dict['category'] = None
        context_dict['pages'] = None
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)




def add_category(request): 
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
# Save the new category to the database. 
            form.save(commit=True)
# Now that the category is saved, we could confirm this. # 
# For now, just redirect the user back to the index view. 
            return redirect('/rango/')
        else:
# The supplied form contained errors -
 # just print them to the terminal.
            print(form.errors)
# Will handle the bad form, new form, or no form supplied cases. # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug): 
    try:
        category = Category.objects.get(slug=category_name_slug) 
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid(): 
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
    
    else: 
        print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


# Use the login_required() decorator to ensure only those logged in can # access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")

def user_login(request):
# If the request is a HTTP POST, try to pull out the relevant information. 
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
# If the account is valid and active, we can log the user in. # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
# An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
# Bad login details were provided. So we can't log the user in. 
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')



def register(request):
    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
# Attempt to grab information from the raw form information. # Note that we make use of both UserForm and UserProfileForm. 
        user_form = UserForm(request.POST)  
        profile_form = UserProfileForm(request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid(): # Save the user's form data to the database. 
            user = user_form.save()
# Now we hash the password with the set_password method. # Once hashed, we can update the user object. 
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
            user_form = UserForm()
            profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  context = {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})



# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val 
    return val
# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1')) 
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
'%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
# Update the last visit cookie now that we have updated the count 
        request.session['last_visit'] = str(datetime.now())
    else:
# Set the last visit cookie 
        request.session['last_visit'] = last_visit_cookie
    # Update/set the visits cookie
    request.session['visits'] = visits

templates/rango/about.html
{%extends'rango/base.html'%} 

{% load staticfiles %}

{%blocktitle_block%} 
   About Rango
{%endblock%}

{%blockbody_block%}   
<h1>Rango says...</h1>
<div>
    here is the about page.<br />
    This tutorial has been put together by jingwen<br />
</div>

<img src="{% static 'images/rango.jpg' %}"
                alt="Picture of Rango" />
<img src="{% MEDIA_URL'cat.jpg' %}"
                alt="Picture of a cat" />    

{% endblock %}

templates/rango/add_category.html
{%extends'rango/base.html'%} 
{% load staticfiles %}

{%blocktitle_block%} 
   Add a Category
{%endblock%}

{%blockbody_block%} 
<h1>Add a Category</h1> 
<div>
    <form id="category_form" method="post" action="/rango/add_category/"> 
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
                {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}

        {% endfor %}
        <input type="submit" name="submit" value="Create Category" /> 
        </form>
        </div> 
{%endblock%}

templates/rango/add_page.html
{%extends'rango/base.html'%} 

{%blocktitle_block%} 
   Add a Page
{%endblock%}


{%blockbody_block%}
<h1>Add a Page</h1> 
<div>
    <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/"> 
        {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                   {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}

            {% endfor %}
            <input type="submit" name="submit" value="Create Page" /> 
        </form>
        </div> 
{%endblock%}

templates/rango/base.html
<!DOCTYPEhtml>
{%loadstaticfiles%}

<html> 
    <head>
        <title>
            Rango -
           {% block title_block %}
               How to Tango with Django!
               {% endblock %} 
            </title>
    </head> 
    <body>
        <div>   
        {% block body_block %} 
        {% endblock %}
        </div>
        <hr />  
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li> {% else %}
                    <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li> {% endif %}
                    <!-- Outside the conditional statements, ALWAYS show -->
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li> <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
                </ul>
        </div>
    </body> 
 </html>

templates/rango/category.html
{%extends'rango/base.html'%} 
{%loadstaticfiles%}

{%blocktitle_block%} 
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{%endblock%}

{%blockbody_block%}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li> 
        {% endfor %}
    </ul>
    {% else %}  
    <strong>No pages currently in category.</strong> 
    {% endif %}

    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br /> 
    {% else %}
    The specified category does not exist.
    {% endif %}
{%endblock%}

templates/rango/index.html
{%extends'rango/base.html'%} 


{%loadstaticfiles%} 


{%blocktitle_block%} 
    Homepage
{%endblock%}


{%blockbody_block%} 
<h1>Rango says...</h1> 
<div>
    hey there partner! <br/> 
    <strong>{{ boldmessage }}</strong>
</div>

<div>  
    <h2>Most liked Categories</h2>
{% if categories %}
     <ul>
        {% for category in categories %} <li>
                <a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }}
                </a> </li>
                {% endfor %}</ul> 
        {% else %}
            <strong>There are no categories present.</strong> 
        {% endif %}
        </div>


        <div>   
            <h2>Most viewd Pages</h2>
        {% if pages %}
            <ul>
            {% for page in pages %} <li>
                    <!-- The following line is changed to add an HTML hyperlink -->
            <a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a> </li>
            {% endfor %} </ul> 
            {% else %}
                <strong>There are no categories present.</strong> 
            {% endif %}
            </div>


        <div>
        <a href="/rango/about/">About Rango</a><br />
         <img src="{% static "images/rango.jpg" %}"
                alt="Picture of Rango" />

        </div> 
{ %endblock%}

templates/rango/register.html
{%extends'rango/base.html'%}
{%loadstaticfiles%}

{%blocktitle_block%}
    Register
{%endblock%}

{%blockbody_block%}
<h1>RegisterforRango</h1>
{%ifregistered%} 
Rangosays:<strong>thankyouforregistering!</strong> 
<ahref="{%url'rango:index'%}">Returntothehomepage.</a><br/> 
{%else%}
Rangosays:<strong>registerhere!</strong><br/> 
<formid="user_form"method="post"action="{%url'rango:register'%}"
enctype="multipart/form-data">

{% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

   <!-- Provide a button to click to submit the form. -->

<input type="submit" name="submit" value="Register" /> 
</form>
{%endif%} 
{%endblock%}

templates/rango/restricted.html
{% extends 'rango/base.html'%}
{%load staticfiles %}

{%block title_block%}
    Restricted Page
{% endblock%}

{%block title_block%}
    <h1>Restricted Page</h1>
    Restrcited
{% endblock%}